<?php
return [
    'welcome' => 'Welcome',
    'settings' => 'Settings',
    'manage_preferences' => 'Manage your account preferences',
    'notifications' => 'Notifications',
    'email_notifications' => 'Email Notifications',
    'sms_notifications' => 'SMS Notifications',
    'preferences' => 'Preferences',
    'language' => 'Language',
    'dark_mode' => 'Dark Mode',
    'save_settings' => 'Save Settings',
    'account' => 'Account',
    'profile' => 'Profile',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'password' => 'Password',
    'email' => 'Email',
    'username' => 'Username',
    'confirm_password' => 'Confirm Password',
    'forgot_password' => 'Forgot Password?',
    'reset_password' => 'Reset Password',
    'remember_me' => 'Remember Me',
    'submit' => 'Submit',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'save' => 'Save',
    'success' => 'Success',
    'error' => 'Error',
    'email_notifications' => 'Email Notifications',
    'sms_notifications' => 'SMS Notifications',
    'language' => 'Language',
    'dark_mode' => 'Dark Mode',
    'save_settings' => 'Save Settings'
];